default_lang: en
lang: en
languages:
- en
- ar
rtl: true
tagline: Al-Ahliya INT. Co. - for General Cleaning Services
theme:
  mode: auto
timezone: Asia/Kuwait
title: AICR
---
analytics:
  cloudflare:
    id: null
  fathom:
    id: null
  goatcounter:
    id: null
  google:
    id: null
  matomo:
    domain: null
    id: null
  umami:
    domain: null
    id: null
assets:
  self_host:
    enabled: null
    env: null
avatar: null
baseurl: ''
cdn: null
collections:
  tabs:
    output: true
    sort_by: order
comments:
  disqus:
    shortname: null
  giscus:
    category: null
    category_id: null
    input_position: null
    lang: null
    mapping: null
    reactions_enabled: null
    repo: null
    repo_id: null
    strict: null
  provider: null
  utterances:
    issue_term: null
    repo: null
compress_html:
  blanklines: false
  clippings: all
  comments: all
  endings: all
  ignore:
    envs:
    - development
  profile: false
defaults:
- scope:
    path: ''
    type: posts
  values:
    comments: true
    layout: post
    permalink: /posts/:title/
    toc: true
- scope:
    path: _drafts
  values:
    comments: false
- scope:
    path: ''
    type: tabs
  values:
    layout: page
    permalink: /:title/
description: 'A Kuwaiti online store features a carefully curated range of cleaning
  products categories: Chemicals, Power Driven, Tools, Trash Management and more.'
exclude:
- '*.gem'
- '*.gemspec'
- docs
- tools
- README.md
- LICENSE
- purgecss.js
- '*.config.js'
- package*.json
github:
  username: TM-TAG
instagram:
  username: alahliyakwt
jekyll-archives:
  enabled:
  - categories
  - tags
  layouts:
    category: category
    tag: tag
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/
kramdown:
  footnote_backlink: '&#8617;&#xfe0e;'
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
      start_line: 1
    css_class: highlight
    span:
      line_numbers: false
pageviews:
  provider: null
paginate: 10
pwa:
  cache:
    deny_paths: null
    enabled: true
  enabled: true
sass:
  style: compressed
social:
  email: TamerBuSalem@gmail.com
  links:
  - https://instagram.com/alahliyakwt
  - https://github.com/TM-TAG
  name: Tamer Bu Salem
social_preview_image: null
theme_mode: null
toc: true
url: ''
webmaster_verifications:
  alexa: null
  baidu: null
  bing: null
  facebook: null
  google: null
  yandex: null
